services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: pastebox_db
    ports:
      - "5432:5432"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pastebox_pgdata_dev:/var/lib/postgresql/data

volumes:
  pastebox_pgdata_dev:
